version: "3.3"
services:
  mongo-container:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SECRET}
    ports:
      - "27017:27017"
    command: mongod
  api:
    build: .
    container_name: api
    expose:
      - $API_PORT
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "$API_PORT"]
  gui:
    build: ./gui
    container_name: api_gui
    expose:
      - 4200
    command:
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
