version: "3.8"
services:
  mongo-container:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SECRET}
    ports:
      - "27017:27017"
    command: mongod